### ISSUE TITLE
Extract daily data with lat/lon

### ISSUE THREAD

**Issue by gagecarto** [sdtaylor/pyPRISMClimate#10]
Is is possible to extract PRISM daily values using a lat/lon, string of variables and start/end date? This feature is available in the PRISM data explorer and seems like it might be possible via url or this Python package, I've just not found the right syntax or examples yet. 

You can see these urls generated by PRISM when using the data explorer. I blacked out what appeared to be a key 

![Capture](https://user-images.githubusercontent.com/5776766/67430110-d0e7c980-f59e-11e9-8b6c-5e55e8094d06.JPG)

**Comment by sdtaylor** [comment]
It certainly looks possible. I can't find any sort of web API for this though, so it is possibly a feature they do not want used beyond their web interface. I don't see similar functionality in the R package either.   
Are you looking to get daily data from just a few sites without having to download all the daily rasters?
